#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="${1:-${OUT_FILE:-$ROOT/release/caiyun-sbom.json}}"
OUT_DIR="$(cd "$(dirname "$OUT_FILE")" && pwd)"
TARGET_DIR="${SBOM_TARGET_DIR:-$OUT_DIR}"

mkdir -p "$OUT_DIR"

if command -v syft >/dev/null 2>&1; then
  syft "dir:$TARGET_DIR" -o "cyclonedx-json=$OUT_FILE"
  echo "SBOM generated by syft: $OUT_FILE"
  exit 0
fi

PYTHON_BIN="${PYTHON_BIN:-python}"
command -v "$PYTHON_BIN" >/dev/null 2>&1 || { echo "python is required for fallback SBOM generation" >&2; exit 1; }
"$PYTHON_BIN" - "$TARGET_DIR" "$OUT_FILE" <<'PY'
from pathlib import Path
import datetime as dt
import hashlib
import json
import sys

target = Path(sys.argv[1])
out = Path(sys.argv[2])
components = []
for item in sorted(target.iterdir(), key=lambda p: p.name):
    if not item.is_file():
        continue
    if item.name == out.name or item.name == 'SHA256SUMS' or item.name.endswith('.sig'):
        continue
    digest = hashlib.sha256(item.read_bytes()).hexdigest()
    components.append({
        "type": "file",
        "name": item.name,
        "hashes": [{"alg": "SHA-256", "content": digest}],
        "properties": [{"name": "size", "value": str(item.stat().st_size)}],
    })

doc = {
    "bomFormat": "CycloneDX",
    "specVersion": "1.5",
    "version": 1,
    "metadata": {
        "timestamp": dt.datetime.utcnow().replace(microsecond=0).isoformat() + "Z",
        "tools": [{"vendor": "caiyun", "name": "generate-sbom.sh", "version": "fallback"}],
        "component": {"type": "application", "name": "caiyun"},
    },
    "components": components,
}
out.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
PY

echo "SBOM generated by fallback scanner: $OUT_FILE"
