#!/usr/bin/env python3
"""Synchronize generated MySQL init SQL copies with backend/migrations/init.sql."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INIT_SQL = ROOT / "backend" / "migrations" / "init.sql"
LEGACY_SQL = ROOT / "backend" / "scripts" / "init_caiyun_database.sql"
K8S_YAML = ROOT / "k8s" / "caiyun.yaml"
SQL_MARKER = "001_init_caiyun_database.sql: |"
LEGACY_HEADER = """-- Auto-generated from backend/migrations/init.sql.
-- Do not edit this file directly. Run: python scripts/sync_k8s_sql.py

CREATE DATABASE IF NOT EXISTS `caiyun`
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE `caiyun`;
"""


def main() -> None:
    sql_lines = [line.rstrip() for line in INIT_SQL.read_text(encoding="utf-8").splitlines()]
    LEGACY_SQL.write_text(LEGACY_HEADER + "\n" + "\n".join(sql_lines) + "\n", encoding="utf-8")

    yaml_lines = K8S_YAML.read_text(encoding="utf-8").splitlines()

    start = next(i for i, line in enumerate(yaml_lines) if line.strip() == SQL_MARKER) + 1
    end = len(yaml_lines)
    for i in range(start, len(yaml_lines)):
        if yaml_lines[i] == "---":
            end = i
            break

    indented_sql = ["    " + line if line else "" for line in sql_lines]
    K8S_YAML.write_text(
        "\n".join(yaml_lines[:start] + indented_sql + yaml_lines[end:]) + "\n",
        encoding="utf-8",
    )
    print(f"synced {INIT_SQL.relative_to(ROOT)} -> {LEGACY_SQL.relative_to(ROOT)}")
    print(f"synced {INIT_SQL.relative_to(ROOT)} -> {K8S_YAML.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
